### ISSUE TITLE
Используя SVG, нарисовать круг произвольного цвета.

### ISSUE THREAD

**Issue by iarovikov** [vadimyarovikov/itten-circle-wheel#1]
SVG - https://ru.wikipedia.org/wiki/SVG

Результатом должен быть HTML-файл с SVG внутри.

**Comment by iarovikov** [comment]
@tima15 Тебе нужно теперь в свой index.html добавить SVG-графику с кругом. Цвет не важен. Ну и запушить новую версию в репозиторий.

**Comment by tima15** [comment]
сделал

**Comment by iarovikov** [comment]
Добавил возможность просматривать результат тут: https://vadimyarovikov.github.io/itten-circle-wheel/
