### ISSUE TITLE
Прочитать краткое руководство по Git и клонировать репозиторий.

### ISSUE THREAD

**Issue by iarovikov** [vadimyarovikov/itten-circle-wheel#2]
Сперва немного ознакомиться что такое системы контроля версий и как с ними работать.

### Гайды по Git

- http://rogerdudler.github.io/git-guide/index.ru.html
- https://proglib.io/p/git-for-half-an-hour/

**Comment by iarovikov** [comment]
@tima15 Добавь пустой index.html файл в корень репозитория.

**Comment by tima15** [comment]
Сделано

**Comment by iarovikov** [comment]
@tima15, а где? Что-то не вижу

**Comment by tima15** [comment]
нуу как я понял мне нужно теперь создать удаленный репозиторий и на него скинуть?

**Comment by iarovikov** [comment]
Тебе надо этот клонировать, в него добавить файл и обратно запушить сюда. То есть создавать ничего нового не нужно.

**Comment by tima15** [comment]
а что прописывается вместо "git push origin master"?

**Comment by iarovikov** [comment]
Ничего, если у тебя уже склонировано, то так и нужно писать. Есть проблемы с пушем?

**Comment by tima15** [comment]
я не знаю почему но до этого писал и не работало, а сейчас заработало, вообщем готово
