### ISSUE TITLE
Познакомиться с принципом ветвления Git

### ISSUE THREAD

**Issue by iarovikov** [vadimyarovikov/itten-circle-wheel#3]
https://git-scm.com/book/ru/v1/%D0%92%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Git-%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-%D0%B2%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B8-%D1%81%D0%BB%D0%B8%D1%8F%D0%BD%D0%B8%D1%8F

**Comment by iarovikov** [comment]
Создать новую ветку с названием blue-rectangle и добавить туда вместо зелёного круга синий прямоугольник, тоже на SVG.

**Comment by tima15** [comment]
я сегодня уже не успею, завтра разберусь и отпишу, ну я помню что завтра вы заняты, так что как уж там получится

**Comment by iarovikov** [comment]
Без проблем.

**Comment by tima15** [comment]
Я выполнил.

**Comment by iarovikov** [comment]
👍 Теперь нажми кнопку Pull Request и создасться реквест. Можно их видеть на вкладке Pull Requests. 
Добавил немного инфы по пулл-реквестам, прочитай: [wiki](https://github.com/vadimyarovikov/itten-circle-wheel/wiki/Pull-requests)

**Comment by tima15** [comment]
Я не совсем понял почему удаляется круг и добавляется треугольник.

**Comment by iarovikov** [comment]
Всм? Что не понял?

**Comment by tima15** [comment]
Получается когда делается Pull Requests происходит слияние, и при этом красным подсвечивается то что будет удалено, а зеленым что будет добавлено?

**Comment by iarovikov** [comment]
А, нет, тут проблема в другом. Ты, когда делал ветку, мастер был в одном состоянии, после этого я добавлял в мастер коммиты. Поэтому и происходит конфликт. 
Почитай тут: http://pr0git.blogspot.com/2015/02/git-1.html

Тебе нужно свою ветку обновить до последней версии, сделать так называемый rebase: 
https://habr.com/post/161009/

**Comment by iarovikov** [comment]
#6
