### ISSUE TITLE
Использование canvas.

### ISSUE THREAD

**Issue by iarovikov** [vadimyarovikov/itten-circle-wheel#7]
Ознакомится с руководством по canvas: https://developer.mozilla.org/ru/docs/Web/API/Canvas_API/Tutorial (там большое руководство, тебе пока нужна только эта страница и следующая https://developer.mozilla.org/ru/docs/Web/API/Canvas_API/Tutorial/Basic_usage)
Задача: справа от синего прямоугольника добавить красный прямоугольник, но уже с ипользованием canvas

**Comment by tima15** [comment]
мне то есть так же нужно создать доп ветку на нее кинуть canvas и потом объединить?

**Comment by iarovikov** [comment]
Да, именно так.

чт, 26 июл. 2018 г. в 17:34, tima15 <notifications@github.com>:

**Comment by tima15** [comment]
а если сделать Pull внести изменения в indes и потом push?

**Comment by iarovikov** [comment]
В ветку master? Он тебе не разрешит, я заблокировал ветку master. Ты
сможешь сделать pull, внести изменения, но вот push не получится сделать.
Так что делай pull мастера, потом делай от этого ветку и после уже вноси
изменения.

чт, 26 июл. 2018 г. в 18:07, tima15 <notifications@github.com>:

**Comment by tima15** [comment]
Хотел сделать pull request но он не видит ветку, в чем может быть проблема?

**Comment by iarovikov** [comment]
А ты пуш сделал ветки?

**Comment by iarovikov** [comment]
@tima15 получилось?

**Comment by tima15** [comment]
я когда делаю git push мне пишет Everything up-to-date

**Comment by iarovikov** [comment]
Хм, странно

**Comment by iarovikov** [comment]
Покажи скриншот

**Comment by tima15** [comment]
![default](https://user-images.githubusercontent.com/41546756/43414650-3de9323c-9455-11e8-82e1-2398148ee5ed.png)

**Comment by iarovikov** [comment]
Так надо не в мастер пушить, а в новую ветку. Можешь просто написать `git push origin`
После origin идёт имя ветки. Ты же не в мастер пушишь

**Comment by tima15** [comment]
понял

**Comment by tima15** [comment]
сделал

**Comment by iarovikov** [comment]
Вижу, давай теперь pull request.

**Comment by tima15** [comment]
его тоже уже сделал

**Comment by tima15** [comment]
а как отменить pull request?

**Comment by iarovikov** [comment]
А тебе не надо отменять. Просто работай дальше в этой ветке, потом коммит и
пуш. И пулл реквест сам обновится.

**Comment by tima15** [comment]
все понял
