### ISSUE TITLE
Вставить картинку в canvas.

### ISSUE THREAD

**Issue by iarovikov** [vadimyarovikov/itten-circle-wheel#8]
Прочитать все статьи в меню слева по поводу canvas выделенные на рисунке
![image](https://user-images.githubusercontent.com/10055385/43154003-2779875e-8f73-11e8-9b91-75821bf19a2b.png)
Используя информацию из статьи https://developer.mozilla.org/ru/docs/Web/API/Canvas_API/Tutorial/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9
нужно вставить в canvas вот эту картинку: https://images.template.net/wp-content/uploads/2015/03/Pixel-Art-Mario.jpg

**Comment by tima15** [comment]
в тот же canvas только вместо красного прямоугольника картинку марио?

**Comment by iarovikov** [comment]
Да

**Comment by tima15** [comment]
У меня вопрос, при загрузке изображения в canvas в html документе нужно сделать загрузку скрипта при отображении страницы или же просто вызвать функцию?

**Comment by iarovikov** [comment]
Не совсем понял, о чем ты? Можешь на примере пояснить?

**Comment by tima15** [comment]
В html пишется это <body onload="drawImage();">, это так же оставлять или просто вызвать скрипт?

**Comment by iarovikov** [comment]
Вызывай скрипт

**Comment by tima15** [comment]
я сделал pull request но вроде там что-то не так как я понял

**Comment by iarovikov** [comment]
Я гляну
