### ISSUE TITLE
Научиться определять цвет пикселя по клику на canvas.

### ISSUE THREAD

**Issue by iarovikov** [vadimyarovikov/itten-circle-wheel#9]
Прочитать все статьи на рисунке 
![image](https://user-images.githubusercontent.com/10055385/43154206-d2c48fd2-8f73-11e8-9156-a842877f8a57.png)
С помощью https://developer.mozilla.org/ru/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas сделать так, чтобы при клике мышкой на canvas в консоли браузера выводился цвет этого пикселя в формате RGB.

**Comment by iarovikov** [comment]
Что такое консоль разработчика и как её использовать, можно прочитать здесь:
https://learn.javascript.ru/devtools

**Comment by tima15** [comment]
А я же могу в случае чего удалить файлы свои и скачать отсюда?

**Comment by iarovikov** [comment]
Да, конечно
